/* eslint-disable */
import {G,L,rb,Za,va} from './geotoolkit.base.js';var aa,ha=ha||{};ha.scope={};ha.Nqc=function(c){var a=0;return function(){return a<c.length?{done:!1,value:c[a++]}:{done:!0}}};ha.Moe=function(c){return{next:ha.Nqc(c)}};ha.qXc=!1;ha.URd=!1;ha.VRd=!1;ha.Mfe=!1;ha.Acc=!1;ha.defineProperty=ha.qXc||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,a,b){if(c==Array.prototype||c==Object.prototype)return c;c[a]=b.value;return c};
ha.cod=function(c){c=["object"==typeof globalThis&&globalThis,c,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var a=0;a<c.length;++a){var b=c[a];if(b&&b.Math==Math)return b}return function(){throw Error("Cannot find global object");}()};ha.global=ha.cod(this);ha.nEb="function"===typeof Symbol&&"symbol"===typeof Symbol("x");ha.hje=!ha.Acc||ha.nEb;ha.r3b={};ha.L3b={};ha.S1c="$jscp$";
function aaa(c,a){var b=ha.L3b[a];if(null==b)return c[a];b=c[b];return void 0!==b?b:c[a]}ha.lKc=function(c,a,b,d){a&&(ha.Acc?ha.ZDd(c,a,b,d):ha.$Dd(c,a,b,d))};ha.$Dd=function(c,a,b,d){b=ha.global;c=c.split(".");for(d=0;d<c.length-1;d++){var e=c[d];if(!(e in b))return;b=b[e]}c=c[c.length-1];d=b[c];a=a(d);a!=d&&null!=a&&ha.defineProperty(b,c,{configurable:!0,writable:!0,value:a})};
ha.ZDd=function(c,a,b,d){var e=c.split(".");c=1===e.length;d=e[0];d=!c&&d in ha.r3b?ha.r3b:ha.global;for(var f=0;f<e.length-1;f++){var g=e[f];if(!(g in d))return;d=d[g]}e=e[e.length-1];b=ha.nEb&&"es6"===b?d[e]:null;a=a(b);null!=a&&(c?ha.defineProperty(ha.r3b,e,{configurable:!0,writable:!0,value:a}):a!==b&&(ha.L3b[e]=ha.nEb?ha.global.Symbol(e):ha.S1c+e,e=ha.L3b[e],ha.defineProperty(d,e,{configurable:!0,writable:!0,value:a})))};ha.Ise=function(){};
ha.lKc("Symbol",function(c){function a(f){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new b(d+(f||"")+"_"+e++,f)}function b(f,g){this.oXc=f;ha.defineProperty(this,"description",{configurable:!0,writable:!0,value:g})}if(c)return c;b.prototype.toString=function(){return this.oXc};var d="jscomp_symbol_",e=0;return a},"es6","es3");ha.Kse=function(){};
ha.lKc("Symbol.iterator",function(c){if(c)return c;c=Symbol("Symbol.iterator");for(var a="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),b=0;b<a.length;b++){var d=ha.global[a[b]];"function"===typeof d&&"function"!=typeof d.prototype[c]&&ha.defineProperty(d.prototype,c,{configurable:!0,writable:!0,value:function(){return ha.Nyd(ha.Nqc(this))}})}return c},"es6","es3");ha.Jse=function(){};
ha.Nyd=function(c){c={next:c};c[Symbol.iterator]=function(){return this};return c};var fE=/*#__PURE__*/va(/*#__PURE__*/function(){function c(b){this.options=G(b,{server:"",metaservice:"json/faultdata",dataservice:"json/faultquery",file:""})}function a(b,d){return encodeURI(b+"?json=")+encodeURIComponent(JSON.stringify({filePath:d}))}L(c,"geotoolkit.intgeo.RemoteFaultPillarDataSource");c.prototype.xbb=function(b,d){var e=new Za.XMLHttpRequest;e.onreadystatechange=function(){if(e.readyState===e.DONE)if(200===e.status&&null!=e.response){var f=JSON.parse(e.response);b(f)}else rb("Failed to download:"+e.status+
" "+e.statusText),d(e)};e.open("GET",a(this.options.server+this.options.metaservice,this.options.file),!0);e.send();return e};c.prototype.wbb=function(b,d){var e=new Za.XMLHttpRequest;e.onreadystatechange=function(){e.readyState===e.DONE&&(200===e.status&&null!=e.response?b(JSON.parse(e.response)):(rb("Failed to download:"+e.status+" "+e.statusText),d(e)))};e.open("GET",a(this.options.server+this.options.dataservice,this.options.file),!0);e.send();return e};return c}(),2,"eyJwcm90b3R5cGUiOnsicyI6MCwiYyI6eyJyZWFkTWV0YWRhdGEiOiJ4YmIiLCJyZWFkRGF0YSI6IndiYiJ9fX0g");var gE=/*#__PURE__*/va(/*#__PURE__*/function(){function c(b){this.options=G(b,{server:"",metaservice:"json/gridsurfacestream",dataservice:"json/gridsurfacestreampts",file:""})}function a(b,d){return encodeURI(b+"?json=")+encodeURIComponent(JSON.stringify({filePath:d}))}L(c,"geotoolkit.intgeo.RemoteGridSurfaceDataSource");c.prototype.xbb=function(b,d){var e=new Za.XMLHttpRequest;e.onreadystatechange=function(){if(e.readyState===e.DONE)if(200===e.status&&null!=e.response){var f=JSON.parse(e.response);b(f)}else rb("Failed to download:"+
e.status+" "+e.statusText),d(e)};e.open("GET",a(this.options.server+this.options.metaservice,this.options.file),!0);e.send();return e};c.prototype.cFd=function(b,d){var e=new Za.XMLHttpRequest;e.onreadystatechange=function(){e.readyState===e.DONE&&(200===e.status&&null!=e.response?b(new Float32Array(e.response)):(rb("Failed to download:"+e.status+" "+e.statusText),d(e)))};e.open("GET",a(this.options.server+this.options.dataservice,this.options.file),!0);e.responseType="arraybuffer";e.send();return e};
return c}(),2,"eyJwcm90b3R5cGUiOnsicyI6MCwiYyI6eyJyZWFkTWV0YWRhdGEiOiJ4YmIiLCJyZWFkRGF0YUFycmF5IjoiY0ZkIn19fSAg");var hE=/*#__PURE__*/va(/*#__PURE__*/function(){function c(b){this.options=G(b,{server:"",metaservice:"json/welldata",dataservice:"json/logcurvedata",file:""})}function a(b,d,e){return null==e?encodeURI(b+"?json=")+encodeURIComponent(JSON.stringify({filePath:d})):encodeURI(b+"?json=")+encodeURIComponent(JSON.stringify({filePath:d,logCurve:e}))}L(c,"geotoolkit.intgeo.RemoteWelllogDataSource");c.prototype.xbb=function(b,d){var e=new Za.XMLHttpRequest;e.onreadystatechange=function(){if(e.readyState===e.DONE)if(200===e.status&&null!=
e.response){var f=JSON.parse(e.response);b(f)}else rb("Failed to download:"+e.status+" "+e.statusText),d(e)};e.open("GET",a(this.options.server+this.options.metaservice,this.options.file),!0);e.send();return e};c.prototype.bFd=function(b,d,e){var f=new Za.XMLHttpRequest;f.onreadystatechange=function(){if(f.readyState===f.DONE)if(200===f.status&&null!=f.response){var g=JSON.parse(f.response);d(g)}else rb("Failed to download:"+f.status+" "+f.statusText),e(f)};f.open("GET",a(this.options.server+this.options.dataservice,
this.options.file,b),!0);f.send();return f};return c}(),2,"eyJwcm90b3R5cGUiOnsicyI6MCwiYyI6eyJyZWFkTWV0YWRhdGEiOiJ4YmIiLCJyZWFkQ3VydmUiOiJiRmQifX19");export {fE,gE,hE};