/* eslint-disable */
import {xb,D,L,bj,G,U,rf,va} from './geotoolkit.base.js';import {gJ,AK,dJ} from './geotoolkit.seismic.js';import {sM,wM,iN} from './geotoolkit.welllog.js';var aa,ha=ha||{};ha.scope={};ha.Nqc=function(c){var a=0;return function(){return a<c.length?{done:!1,value:c[a++]}:{done:!0}}};ha.Moe=function(c){return{next:ha.Nqc(c)}};ha.qXc=!1;ha.URd=!1;ha.VRd=!1;ha.Mfe=!1;ha.Acc=!1;ha.defineProperty=ha.qXc||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,a,b){if(c==Array.prototype||c==Object.prototype)return c;c[a]=b.value;return c};
ha.cod=function(c){c=["object"==typeof globalThis&&globalThis,c,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var a=0;a<c.length;++a){var b=c[a];if(b&&b.Math==Math)return b}return function(){throw Error("Cannot find global object");}()};ha.global=ha.cod(this);ha.nEb="function"===typeof Symbol&&"symbol"===typeof Symbol("x");ha.hje=!ha.Acc||ha.nEb;ha.r3b={};ha.L3b={};ha.S1c="$jscp$";
function aaa(c,a){var b=ha.L3b[a];if(null==b)return c[a];b=c[b];return void 0!==b?b:c[a]}ha.lKc=function(c,a,b,d){a&&(ha.Acc?ha.ZDd(c,a,b,d):ha.$Dd(c,a,b,d))};ha.$Dd=function(c,a,b,d){b=ha.global;c=c.split(".");for(d=0;d<c.length-1;d++){var e=c[d];if(!(e in b))return;b=b[e]}c=c[c.length-1];d=b[c];a=a(d);a!=d&&null!=a&&ha.defineProperty(b,c,{configurable:!0,writable:!0,value:a})};
ha.ZDd=function(c,a,b,d){var e=c.split(".");c=1===e.length;d=e[0];d=!c&&d in ha.r3b?ha.r3b:ha.global;for(var f=0;f<e.length-1;f++){var g=e[f];if(!(g in d))return;d=d[g]}e=e[e.length-1];b=ha.nEb&&"es6"===b?d[e]:null;a=a(b);null!=a&&(c?ha.defineProperty(ha.r3b,e,{configurable:!0,writable:!0,value:a}):a!==b&&(ha.L3b[e]=ha.nEb?ha.global.Symbol(e):ha.S1c+e,e=ha.L3b[e],ha.defineProperty(d,e,{configurable:!0,writable:!0,value:a})))};ha.Ise=function(){};
ha.lKc("Symbol",function(c){function a(f){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new b(d+(f||"")+"_"+e++,f)}function b(f,g){this.oXc=f;ha.defineProperty(this,"description",{configurable:!0,writable:!0,value:g})}if(c)return c;b.prototype.toString=function(){return this.oXc};var d="jscomp_symbol_",e=0;return a},"es6","es3");ha.Kse=function(){};
ha.lKc("Symbol.iterator",function(c){if(c)return c;c=Symbol("Symbol.iterator");for(var a="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),b=0;b<a.length;b++){var d=ha.global[a[b]];"function"===typeof d&&"function"!=typeof d.prototype[c]&&ha.defineProperty(d.prototype,c,{configurable:!0,writable:!0,value:function(){return ha.Nyd(ha.Nqc(this))}})}return c},"es6","es3");ha.Jse=function(){};
ha.Nyd=function(c){c={next:c};c[Symbol.iterator]=function(){return this};return c};var pP=/*#__PURE__*/va(/*#__PURE__*/function(){function c(a,b,d,e,f){a=xb(a,{pipeline:a instanceof gJ?a:null},!0);AK.call(this,a,b,d,e,f);a=d;this.Kc(null).translate(0,-a).scale(1,1/(f-a)).rotate(Math.PI/2,.5,.5).scale(1,f-a).translate(0,a)}D(c,AK);L(c,"geotoolkit.seislog.WaveSeismicImage");c.prototype.sa=function(a,b,d,e){AK.prototype.sa.call(this,a,b,d,e);a=this.ga().ka();b=this.ga().ma();this.Kc(null).translate(0,-a).scale(1,1/(b-a)).rotate(Math.PI/2,.5,.5).scale(1,b-a).translate(0,a);return this};c.prototype.Ag=function(a,
b){void 0===a&&(a=this.pa());AK.prototype.Ag.call(this,a,b);return this};return c}(),2,"eyJwcm90b3R5cGUiOnsicyI6MCwiYyI6eyJzZXRCb3VuZHMiOiJzYSIsImludmFsaWRhdGVQYXJlbnQiOiJBZyJ9fX0g");var qP=/*#__PURE__*/va(/*#__PURE__*/function(){function c(b){wM.call(this,b);this.kn=new bj;this.kn.fw(2);this.jn=new bj;this.jn.fw(2);var d={visible:!0,text:"",verticalpos:"top",horizontalpos:"center"};b={gap:5,priority:["Name","ScaleFrom","ScaleTo"],order:["Name","ScaleFrom","ScaleTo"]};var e=G(d,{});G({updatemethod:a.n$b,cut:"left-to-right",textstyle:this.jb().clone()},e);var f=G(d,{});G({updatemethod:function(g){g=g.cd();if(!g)return"";g=g.Ii().m4();g=g.limits.Ua()*g.scale;return this.kn.format(g)}.bind(this),textstyle:this.jb().clone(),
horizontalpos:"left"},f);d=G(d,{});G({updatemethod:function(g){g=g.cd();if(!g)return"";g=g.Ii().m4();g=g.limits.Za()*g.scale;return this.jn.format(g)}.bind(this),textstyle:this.jb().clone(),horizontalpos:"right"},d);this.zi("ScaleFrom",f);this.zi("Name",e);this.zi("ScaleTo",d);this.xt(b);this.Ha(new U(0,0,100,40));this.sa(new U(0,0,100,40))}var a=sM;D(c,wM);L(c,"geotoolkit.seislog.headers.AdaptiveSeismicImageHeader");c.prototype.render=function(b){var d=null!=this.Qa()?b.Zb(this.Qa()):b,e=this.cd();
if(null!=e)if(d.ac())this.St(d,rf.kh);else if(this.zi("Name",{text:this.cd().Da()}),wM.prototype.render.call(this,b),null!=e.Ii().a_()){var f=e.Ii().a_().getSize();if(0!==f&&(e=dJ.ag().$6a(e.Ii().ta().colors.colorMap,f),null!==e)){b=this.pa().clone();var g=e.uc(),h=e.Dc(),k=b.ca()/f,l=b.da()/2,m=b.la();f=(h-g)/f;g+=f/2;for(d.ra(null);m<b.na();)d.qa(new rf(e.rb(g).Nl())),d.sc(m,b.ma()-l,k,l),g+=f,m+=k}}};c.prototype.Ba=function(b){this.kn=b.kn;this.jn=b.jn;this.Ha(b.pa());this.sa(b.ga());return this};
c.prototype.yD=function(){return this.kn};c.prototype.xD=function(){return this.jn};c.prototype.c0=function(b){this.kn=b;return this};c.prototype.Yoa=function(b){this.jn=b;return this};iN.ig().lN(AK.Oa(),new c);iN.ig().lN(pP.Oa(),new c);return c}(),2,"eyJwcm90b3R5cGUiOnsicyI6MCwiYyI6eyJjb3B5Q29uc3RydWN0b3IiOiJCYSIsImdldE1pblZhbHVlRm9ybWF0IjoieUQiLCJnZXRNYXhWYWx1ZUZvcm1hdCI6InhEIiwic2V0TWluVmFsdWVGb3JtYXQiOiJjMCIsInNldE1heFZhbHVlRm9ybWF0IjoiWW9hIn19fSAg");export {pP,qP};